# Generated by Django 5.2 on 2025-05-26 04:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deposit_type', models.CharField(choices=[('normal', 'Normal'), ('purchase', 'Purchase')], default='normal', max_length=50)),
                ('transaction_note', models.CharField(blank=True, max_length=250, null=True)),
                ('deposit_reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('deposit_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcms_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_status', models.CharField(choices=[('pending', 'Pending'), ('repaid', 'Repaid'), ('partially repaid', 'Partially Repaid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('loan_reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mcms_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('repayment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mcms_app.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['brand', 'name'],
                'unique_together': {('name', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('motorcycle_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='mcms_app.motorcycle')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
                'ordering': ['motorcycle_model'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(blank=True, help_text='Unique payment reference number', max_length=50, null=True, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Total amount paid to supplier', max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash')], default='BANK_TRANSFER', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mcms_app.supplier')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_reference', models.CharField(blank=True, help_text='Auto-generated delivery reference number', max_length=50, null=True, unique=True)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='mcms_app.supplierpayment')),
            ],
            options={
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('withdrawal_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('withdrawal_status', models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcms_app.deposit')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('SUPPLIER_DELIVERY', 'Supplier Delivery'), ('DELIVERY_REVERSAL', 'Delivery Reversal'), ('SALE', 'Sale')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for additions, negative for reductions')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('reference_model', models.CharField(help_text='Model name that triggered this transaction', max_length=50)),
                ('reference_id', models.PositiveIntegerField(help_text='ID of the record that triggered this transaction')),
                ('remarks', models.TextField(blank=True)),
                ('motorcycle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='mcms_app.motorcycle')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['motorcycle_model', 'transaction_date'], name='mcms_app_in_motorcy_395528_idx'), models.Index(fields=['reference_model', 'reference_id'], name='mcms_app_in_referen_85b980_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierDeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_quantity', models.PositiveIntegerField()),
                ('delivery_remarks', models.TextField(blank=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='mcms_app.supplierdelivery')),
                ('motorcycle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='mcms_app.motorcycle')),
            ],
            options={
                'unique_together': {('delivery', 'motorcycle_model')},
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('motorcycle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='mcms_app.motorcycle')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='mcms_app.supplierpayment')),
            ],
            options={
                'unique_together': {('payment', 'motorcycle_model')},
            },
        ),
    ]
