# Generated by Django 5.2 on 2025-05-27 00:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, help_text='Total amount paid to supplier', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='supplierpaymentitem',
            name='expected_quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='supplierpaymentitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
