# Generated by Django 5.2 on 2025-05-27 15:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcms_app', '0002_alter_supplierpayment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('SUPPLIER_DELIVERY', 'Supplier Delivery'), ('DELIVERY_REVERSAL', 'Delivery Reversal'), ('SALE', 'Sale'), ('SALE_REVERSAL', 'Sale Reversal')], max_length=20),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(default=django.utils.timezone.now, help_text='Date of sale.')),
                ('payment_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('LOAN', 'Loan'), ('CASH', 'Cash'), ('TRANSFER', 'Bank Transfer')], max_length=20)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('engine_no', models.CharField(help_text='Unique engine number.', max_length=100, unique=True)),
                ('chassis_no', models.CharField(help_text='Unique chassis number.', max_length=100, unique=True)),
                ('remarks', models.TextField(blank=True, help_text='Optional remarks about the sale.', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('sale_reference', models.CharField(blank=True, help_text='Auto-generated unique sale reference.', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='mcms_app.customer')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='mcms_app.motorcycle')),
            ],
            options={
                'verbose_name': 'Sale Record',
                'verbose_name_plural': 'Sale Records',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_loan', to='mcms_app.sale'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_withdrawal', to='mcms_app.sale'),
        ),
    ]
