# Generated by Django 5.2 on 2025-05-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcms_app', '0003_alter_inventorytransaction_transaction_type_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DISCONTINUED', 'Discontinued')], db_index=True, default='ACTIVE', help_text='Current status of the motorcycle model.', max_length=20),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
