# Generated by Django 5.2 on 2025-05-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcms_app', '0004_motorcycle_created_at_motorcycle_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-loan_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='loanrepayment',
            options={'ordering': ['-repayment_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
