# Generated by Django 5.2 on 2025-05-30 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcms_app', '0005_alter_loan_options_alter_loanrepayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of sale.'),
        ),
    ]
