# Generated by Django 5.2 on 2025-05-30 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcms_app', '0006_alter_sale_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
