# Generated by Django 5.2 on 2025-06-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcms_app', '0009_customer_created_at_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-loan_date']},
        ),
        migrations.AlterModelOptions(
            name='loanrepayment',
            options={'ordering': ['-repayment_date']},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date'], 'verbose_name': 'Sale Record', 'verbose_name_plural': 'Sale Records'},
        ),
        migrations.AlterModelOptions(
            name='supplierdelivery',
            options={'ordering': ['-delivery_date']},
        ),
        migrations.AlterModelOptions(
            name='supplierpayment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.RemoveField(
            model_name='loan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='loanrepayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplierdelivery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplierpayment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='deposit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
